### ISSUE TITLE
Vault TOTP built-in

### ISSUE THREAD

**Issue by candlerb** [Luzifer/vault-totp#3]
Neat project.

FYI, Vault now has [TOTP generation](https://www.vaultproject.io/docs/secrets/totp) built-in:

```
$ vault secrets enable totp

$ vault write totp/keys/ubuntu url="otpauth://totp/Vault:ubuntu?secret=XXXXXXXX"
  # or: generate=true

$ vault read totp/code/ubuntu
Key     Value
---     -----
code    886531
```

**Comment by Luzifer** [comment]
It already had when I wrote this. As I don't like systems locking in my secrets and having no way to get the secrets back out the built-it TOTP module is unusable for me. You can put in the secret/key but you cannot get it back so if you decide to move to another solution (which I partially did) you will not be able to.
